# Generated by Django 4.0.1 on 2024-06-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='languages',
            field=models.ManyToManyField(to='home.Language'),
        ),
    ]
