# Generated by Django 4.0.1 on 2024-06-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_duration_instructor_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
